server:
  port: 9001

spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_base?characterfEncoding=utf-8
    username: root
    password: zhouhai
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
